### ISSUE TITLE
安装完成之后插件卡死机，只能结束后台进程

### ISSUE THREAD

**Issue by MoCo1134** [std-microblock/BetterNCM-Installer#65]
![QQ图片20230908101924](https://github.com/MicroCBer/BetterNCM-Installer/assets/142894605/66137cb0-edc8-4c3c-8dc1-63aff903cf77)
安装的版本：
![QQ图片20230908102959](https://github.com/MicroCBer/BetterNCM-Installer/assets/142894605/ec4306c0-624c-4613-b5ec-eb4ffc3b916e)
网易云版本：2.10.12

**Comment by MoCo1134** [comment]
之前安装的老版本一点事情没有，后来更新到最新版本之后就开始卡死，更新重装之后依旧死机

**Comment by MicroCBer** [comment]
请发送插件列表

**Comment by sktkyo** [comment]
> 请发送插件列表

跟插件列表没关系，BCM 1.3.4版本后，只有64位的能正常启动，32位的都启动不了，从客户端2.10.*-3.0.*全版本不行。

**Comment by sktkyo** [comment]
> 请发送插件列表

已解决，缺少微软运行库，建议在安装的时候更新这一个提示。
